# Generated by Django 6.0.2 on 2026-02-25 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE orders_order ALTER COLUMN order_number DROP NOT NULL;',
            reverse_sql='ALTER TABLE orders_order ALTER COLUMN order_number SET NOT NULL;',
        ),
        migrations.RunSQL(
            sql='ALTER TABLE orders_order ALTER COLUMN email DROP NOT NULL;',
            reverse_sql='ALTER TABLE orders_order ALTER COLUMN email SET NOT NULL;',
        ),
    ]

