name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create enviornment file
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Check Docker Compose
        run: docker compose version

      - name: Start database
        run: docker compose up -d db

      - name: Wait for database
        run: |
          sleep 10

      - name: Build backend
        run: docker compose build backend

      - name: Run Django tests
        run: docker compose run --rm backend python manage.py test

      - name: Stop containers
        if: always()
        run: docker compose down